server:
  port: 80
spring:
  jmx:
    enabled: false
      #main:
    #allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    url: jdbc:mysql://localhost:3306/wegame?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: wswbh

mybatis:
  configuration:
    map-underscore-to-camel-case: true
